language: java

jdk:
  - openjdk15
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: abwZ67OoHKQUJI9KEueCm3SSCQr+ajdlaSjFSvPdY8nGOA2I7QeB7660sLcviPzPLxpfObyHXbKS+fdeij5vJA9tRrAG0MbCqjYRZ1b66PoJRI0CJI4HnowRWFbIX5Es/0FHOtKMmhLrN5/gsD1HXB94jc/wPHTiSz+CHRrGKr1o8iVGp54D7LG8flRLch4vhqFrQ1jtx7HrbdByC8QEUpFHIXiea+G84uqSmUHHH2R1aOacDpHTmXQ8LIahD4rqRIujFfigGlGVMMFDnlXtGE0OEyl950vhemc8iKc9lOYcvODN6SsHipwG+j/Amti+tf9UJxlSiESFpuE8PD+ZBt/ToCbhWWiTtoFi6xY5bc8qFtnDcvdCFC0/W5x/V/80kickHN0niqWq3ep+qJgbeo2vp7qOJKP7STvK0TUagNSu5kTEiSiihW3Uie1siesMqW1niiQK+qWmCwVnUMcvcbY1sAl13sQzSh9rlQN5+tcxIMC/NguA8/0VQrhGd8Y4mDzdNSP1u8em1V9/gPG62wBa4dPvY82zMxr7TTC+rQ6T/4ddwMiFeRAsjuaW8WoBTS7wvnrUbO5ky+wqcAjZRZaY91hxjjPKbqQawQOAKRzeAVtNV4mCDCxBZ901wy3pnz8mqwsJjBac0hxPOvHiVpnHt25ADEcf1nw/Y9NxEUc=
    - secure: V//tML8d01sMRBqKn6e4W78//GTRunzHuQG3qOcRNkVfYXGPD0d4XGhy+4fDh79atQkV/hf84B50k4fS/HU+z/rRapW6ioc5eLobmy/hwOKTOSlYTwcWwBoGcapHdLcoerWsteE4/IEkrJ7+fSJYJxk5zGBIEHJ9pN++LEly0/8rgpsb8a4evSHwSvJja9ACA2/svwf8exCad2POy59bPdrcNhQmYh7eMX9I+cX0ZYIP+SBD3WZzes4jBnMN302pU/7JyOPV6MwiTkmeNhU2kZ+Oip2Utk7EWZfM+KDxr4kMTds0EeUt0VWJsQX6HkuyXxTkHHiS19aBDTQKk90ZZROBcEho4bI8tw/Qs6mQ9TkVn4dzuDSEfn0Ikob6o5HJX/NTze+zQ+zJb0xFlv+XAwiVZhy3CQ0qsbMbgPFQVOENBq9H51hnNV0GsUwvN1mghE5h/VtbmdNbqgkbwNGOVhaXEMnijhtruA6lt7HPInCCngcZimJ0YC6TkIINuLT40W4lCyVsHyttKfS1wbL2Pp4j621RRLc2eg/93bXzGR0P7IEBMjvRvzjwdKg7vh88AWY/BkV1lSxQP6K4rMGo+Ny6elxPROAFiz5xTc79FzHTR26Z5TLXp61/6O3q8sD3e/JCIF9BSleyCG0LjJDhzuz3ePp8x0DRvPXG/ATGni0=
